CPPFLAGS += -W -Wall -std=c++11 -g
CPPFLAGS += -I ../../include
CPPFLAGS += -I /cygdrive/c/Usr/Xilinx2015.2/Vivado_HLS/2015.2/include

CPPFLAGS += -DNDEBUG=1 -O3

CPPFLAGS += -Wno-unknown-pragmas

LDLIBS += -lmpfr -lgmpxx -lgmp
