:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF
setlocal ENABLEDELAYEDEXPANSION
:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Cyclone10GX"
if not "%2"=="" set "DEVICE=%2"


  i++ -std=c++14 -march=%DEVICE% -I ../../../include -O3 -DNDEBUG=1 -Wno-unknown-pragmas -DTHLS_SYNTHESIS=1 -DTHLS_FW_UINT_ON_AC_UINT=1  dot_product.cpp -o dot_product-fpga.exe
  if not ERRORLEVEL 0 (
    echo Error: Compile failed
    exit /b 1
  )
